/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function __senpiGrepAbi1(): string

export declare function grep(options: GrepOptions, signal?: AbortSignal | undefined | null): Promise<GrepResult>

export interface GrepCounts {
  matches: number | null
  files: number
  exact: boolean
}

export interface GrepFileCount {
  path: string
  count: number | null
  limitReached: boolean
}

export interface GrepMatch {
  path: string
  line: number
  column?: number
  text: string
  isContext: boolean
  truncated: boolean
}

export declare const enum GrepMode {
  Content = 'content',
  Count = 'count',
  Files = 'files'
}

/** The frozen engine request. Pattern recovery and facade defaults belong in TS. */
export interface GrepOptions {
  pattern: string
  paths: Array<string>
  cwd: string
  glob?: Array<string>
  type?: string
  ignoreCase?: boolean
  literal?: boolean
  multiline?: boolean
  hidden?: boolean
  gitignore?: boolean
  maxCount?: number
  maxCountPerFile?: number
  contextBefore?: number
  contextAfter?: number
  maxColumns?: number
  mode?: GrepMode
  timeoutMs?: number
  lineStart?: number
  lineEnd?: number
  pcre2?: boolean
}

export interface GrepResult {
  matches: Array<GrepMatch>
  fileCounts: Array<GrepFileCount>
  counts: GrepCounts
  filesSearched: number
  limitReached: boolean
  perFileLimitReached: boolean
  skippedOversized: number
  prefixSearched: number
  skippedBinary: number
  missingPaths: Array<string>
  warnings: Array<GrepWarning>
  timedOut: boolean
  elapsedMs: number
  effectivePattern: string
  patternKind: 'regex' | 'sanitized' | 'literal'
  regexEngine: 'rust' | 'pcre2'
}

export interface GrepWarning {
  path?: string
  code: string
  message: string
}
