// Core session management

export { sanitizeTerminalLabel, visibleWidth } from "@earendil-works/pi-tui";
export { type Args, parseArgs } from "./cli/args.ts";
// The shared-daemon command surface: one JSON line, one exit code, for launchers without a shell
export { runHostCommand } from "./cli/host-command.ts";
// Config paths
export {
	CONFIG_DIR_NAME,
	getAgentDir,
	getDocsPath,
	getExamplesPath,
	getPackageDir,
	getReadmePath,
	VERSION,
} from "./config.ts";
export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	parseSkillBlock,
	type SessionStats,
} from "./core/agent-session.ts";
export { type OAuthCredential, readStoredCredential } from "./core/auth-storage.ts";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CacheFriendlySummaryOptions,
	type CollectEntriesResult,
	type CompactionResult,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateTokens,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	generateSummaryWithUsage,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./core/compaction/index.ts";
// Engine build identity: the ordinal clients compare instead of version strings
export {
	compareEngineOrdinal,
	type EngineBuildIdentity,
	type EngineBuildInput,
	type EngineOrdinal,
	type EngineOrdinalScheme,
	engineBuildIdentity,
	engineBuildIdentityFrom,
} from "./core/engine-build-identity.ts";
export { createEventBus, type EventBus, type EventBusController } from "./core/event-bus.ts";
export {
	type CancelReceipt,
	EVAL_HANDLE_ERROR_CODES,
	EvalHandleError,
	type EvalHandleErrorCode,
	type EvalHandleHost,
	type HandleCallContext,
	type HandleError,
	type HandleKind,
	type HandleOutcome,
	type HandlePhase,
	type HandleRef,
	type HandleSnapshot,
	type HandleWatch,
	type OutputRequest,
	type OutputSnapshot,
} from "./core/extensions/eval-handle-host.ts";
// Extension system
export type {
	AfterProviderResponseEvent,
	AgentActivityOutcome,
	AgentBeforeSettleEvent,
	AgentBeforeSettleEventResult,
	AgentEndEvent,
	AgentSettledEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppKeybinding,
	AutocompleteProviderFactory,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderHeadersEvent,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	BoundaryContextPreview,
	BoundaryResult,
	BoundaryState,
	BuildSystemPromptOptions,
	CompactionEntryDraft,
	CompactOptions,
	ContextEditEntryDraft,
	ContextEvent,
	ContextEventResult,
	ContextUsage,
	ContextWithSystemEvent,
	CustomEntryDraft,
	CustomMessageEntryDraft,
	CustomToolCallEvent,
	EditToolCallEvent,
	EntryRenderer,
	EntryRendererOptions,
	EntryRenderOptions,
	ExecOptions,
	ExecResult,
	ExecuteToolOptions,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRpcRequestHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionToolContext,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionVirtualModel,
	ExtensionWidgetOptions,
	FilesystemOperation,
	FilesystemPolicy,
	FilesystemPolicyChecker,
	FilesystemPolicyDecision,
	FilesystemPolicyRequest,
	FindToolCallEvent,
	GrepToolCallEvent,
	InlineExtension,
	InputDispositionEvent,
	InputEvent,
	InputEventResult,
	InputSource,
	KernelPreludeContribution,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MarkdownTransformContext,
	MarkdownTransformer,
	McpServerDeclaration,
	MessageEndEvent,
	MessageEndEventResult,
	MessageRenderer,
	MessageRenderOptions,
	MessageStartEvent,
	MessageUpdateEvent,
	ModelSelectEvent,
	ModelSelectSource,
	NormalizedBuildSystemPromptOptions,
	PowerShellToolCallEvent,
	ProjectTrustContext,
	ProjectTrustEvent,
	ProjectTrustEventDecision,
	ProjectTrustEventResult,
	ProjectTrustHandler,
	ProviderConfig,
	ProviderModelConfig,
	ProviderStreamEvent,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	ResolvedCommand,
	ResourcesDiscoverEvent,
	ResourcesDiscoverResult,
	SessionBeforeCompactEvent,
	SessionBeforeCompactResult,
	SessionBeforeForkEvent,
	SessionBeforeForkResult,
	SessionBeforeSwitchEvent,
	SessionBeforeSwitchResult,
	SessionBeforeTreeEvent,
	SessionBeforeTreeResult,
	SessionBoundaryDraft,
	SessionCompactEvent,
	SessionCompactFailedEvent,
	SessionInfoChangedEvent,
	SessionParkedEvent,
	SessionResumedEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandSource,
	SourceInfo,
	TerminalInputHandler,
	ThinkingLevelSelectEvent,
	ToolAnnotations,
	ToolCallEvent,
	ToolCallEventResult,
	ToolDefinition,
	ToolExecutionEndEvent,
	ToolExecutionMode,
	ToolExecutionStartEvent,
	ToolExecutionUpdateEvent,
	ToolExposure,
	ToolInfo,
	ToolLoadout,
	ToolLoadoutChanges,
	ToolNamespace,
	ToolPermissionRequest,
	ToolRenderResultOptions,
	ToolResultEvent,
	ToolResultEventResult,
	TurnEndEvent,
	TurnEndEventResult,
	TurnStartEvent,
	UIPromptEndEvent,
	UIPromptKind,
	UIPromptStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WidgetPlacement,
	WorkingIndicatorOptions,
	WriteToolCallEvent,
} from "./core/extensions/index.ts";
export {
	createExtensionRuntime,
	defineTool,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isPowerShellToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
} from "./core/extensions/index.ts";
export {
	type ExtensionKernelTools,
	type KernelToolInvokeOptions,
	type KernelToolInvokeScope,
	kernelToolsStorage,
} from "./core/extensions/kernel-tools-context.ts";
// Notice primitives
export {
	buildNoticeBox,
	type NoticeLine,
	type NoticeSpec,
	type NoticeTone,
	noticeEntryRenderer,
	noticeMessageRenderer,
} from "./core/extensions/notice/index.ts";
export * from "./core/extensions/session-control-types.ts";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.ts";
export { convertToLlm } from "./core/messages.ts";
export { ModelRegistry } from "./core/model-registry.ts";
export {
	type ModelScopeDiagnostic,
	type ResolveCliModelResult,
	type ResolveModelScopeResult,
	resolveCliModel,
	resolveModelScopeWithDiagnostics,
	type ScopedModel,
} from "./core/model-resolver.ts";
export {
	type CreateModelRuntimeOptions,
	CredentialSynchronizationError,
	type CredentialSynchronizationOperation,
	ModelRuntime,
	type ModelRuntimeAuthOverrides,
} from "./core/model-runtime.ts";
export type {
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./core/package-manager.ts";
export { DefaultPackageManager } from "./core/package-manager.ts";
// Process memory footprint (phys_footprint / RssAnon / PrivateUsage), read without spawning
export {
	type ProcessFootprint,
	type ProcessFootprintMeasure,
	readOwnFootprint,
	readProcessFootprint,
} from "./core/process-footprint.ts";
export type { ResourceCollision, ResourceDiagnostic, ResourceLoader } from "./core/resource-loader.ts";
export { DefaultResourceLoader, loadProjectContextFiles } from "./core/resource-loader.ts";
// SDK for programmatic usage
export {
	AgentSessionRuntime,
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	type CreateAgentSessionServicesOptions,
	// Factory
	createAgentSession,
	createAgentSessionFromServices,
	createAgentSessionRuntime,
	createAgentSessionServices,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createFindTool,
	createGrepTool,
	createLsTool,
	createPowerShellTool,
	createReadOnlyTools,
	createReadTool,
	createWriteTool,
	type PromptTemplate,
} from "./core/sdk.ts";
export {
	type BranchSummaryEntry,
	buildContextEntries,
	buildSessionContext,
	buildSessionProjection,
	type CompactionEntry,
	type ContextEditableContent,
	type ContextEditEntry,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getLatestCompactionEntry,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	type ProjectedSessionEntry,
	parseSessionEntries,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	SessionManager,
	type SessionMessageEntry,
	type SessionProjection,
	type SessionTreeNode,
	sessionEntryToContextMessages,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.ts";
export {
	type CompactionModelOverride,
	type CompactionSettings,
	type DefaultProjectTrust,
	type FullscreenExitOutput,
	type ImageSettings,
	type PackageSource,
	type QuietStartup,
	type RetrySettings,
	SettingsManager,
	type SettingsManagerCreateOptions,
	type TuiMode,
} from "./core/settings-manager.ts";
// Skills
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
} from "./core/skills.ts";
export { createSyntheticSourceInfo } from "./core/source-info.ts";
export { type EditDiffResult, generateDiffString, generateUnifiedPatch } from "./core/tools/edit-diff.ts";
// Tools
export {
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	createBashToolDefinition,
	createEditToolDefinition,
	createFindToolDefinition,
	createGrepToolDefinition,
	createLocalBashOperations,
	createLsToolDefinition,
	createReadToolDefinition,
	createWriteToolDefinition,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	formatSize,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	type LsOperations,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type WriteOperations,
	type WriteToolInput,
	type WriteToolOptions,
	withFileMutationQueue,
} from "./core/tools/index.ts";
export {
	type CompactReadClassification,
	classifyRead,
	type ReadClassifier,
	registerReadClassifier,
} from "./core/tools/read-classifiers.ts";
export {
	hasTrustRequiringProjectResources,
	type ProjectTrustDecision,
	ProjectTrustStore,
	type ProjectTrustStoreEntry,
	type ProjectTrustUpdate,
} from "./core/trust-manager.ts";
export { UnknownCommandError, type UnknownCommandReason } from "./core/unknown-command.ts";
export {
	type ModelRoute,
	type ModelRouteReason,
	type ModelRouteRequest,
	VIRTUAL_MODEL_STATE_ENTRY,
	type VirtualModelDefinition,
	type VirtualModelStateData,
} from "./core/virtual-models.ts";
// Main-thread Bun.WebView service for eval kernels running in worker threads
export { connectWebViewService, type WebViewServiceConnection } from "./core/webview/webview-broker.ts";
// Main entry point
export { type MainOptions, main } from "./main.ts";
// Run modes for programmatic SDK usage
export {
	classifyEndpointLiveness,
	createHostDaemonPaths,
	DEFAULT_HOST_LAUNCH_SPEC,
	daemonDirectoryName,
	decideHostAction,
	ENDPOINT_REGISTRY_VERSION,
	type EndpointKind,
	type EndpointLiveness,
	type EnsuredHost,
	type EnsureHostOptions,
	endpointProbeTimeoutMs,
	ensureHost,
	GENERATION_HANDOFF_CAPABILITY,
	gcHostEndpoints,
	type HandoffHostOptions,
	type HandoffRefusal,
	type HandoffResult,
	HOST_EXIT_ERROR,
	HOST_EXIT_FALLBACK,
	HOST_EXIT_OK,
	HOST_EXIT_REFUSED,
	HOST_EXIT_USAGE,
	HOST_PROTOCOL_VERSION,
	type HostAction,
	type HostDaemonPaths,
	type HostDecision,
	type HostDecisionClient,
	type HostDecisionPolicy,
	type HostDecisionWarning,
	type HostEndpointEntry,
	type HostEndpointIdentitySource,
	type HostEndpointStatus,
	HostEnsureRefusedError,
	type HostGcOptions,
	type HostGcResult,
	type HostGenerationRow,
	type HostLaunchSpec,
	type HostLaunchSpecCore,
	HostLaunchSpecError,
	type HostLaunchSpecRefusal,
	type HostOutcome,
	type HostProtocolInfo,
	type HostRefusalReason,
	type HostRequest,
	type HostSessionCounts,
	type HostStatusOptions,
	type HostStatusReport,
	type HostTarget,
	type HostUpgradePolicy,
	handoffHost,
	InteractiveMode,
	type InteractiveModeOptions,
	isTransportGoneError,
	type JsonAgentSessionEvent,
	listHostEndpoints,
	loadHostLaunchSpec,
	type ModelInfo,
	PINNED_HOST_CLIENT_CAPABILITIES,
	type PrintModeOptions,
	type ProbeHostOptions,
	parseHostLaunchSpec,
	parseHostProtocolInfo,
	probeHost,
	REQUIRED_HOST_CAPABILITIES,
	type ResolvedHostLaunchSpec,
	RpcClient,
	type RpcClientEvent,
	RpcClientOpenInFlightError,
	type RpcClientOptions,
	type RpcCommand,
	type RpcEventListener,
	type RpcExtensionEvent,
	type RpcExtensionUIRequest,
	type RpcExtensionUIResponse,
	type RpcResponse,
	type RpcSessionState,
	RpcTransportGoneError,
	readAllHostStatus,
	readHostStatus,
	runHostRequest,
	runPrintMode,
	runRpcMode,
	type ShardKind,
	type StopHostOptions,
	type StopHostResult,
	shardKey,
	shardSocketPath,
	shardSocketPathForKey,
	stopHost,
	TUI_PROBE_TIMEOUT_MS,
} from "./modes/index.ts";
// UI components for extensions
export {
	ArminComponent,
	AssistantMessageComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	type CustomEditorOptions,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	LoginDialogComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.ts";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeAppearance,
	type ThemeBg,
	type ThemeColor,
	type ThemeStyle,
	type ThemeToken,
} from "./modes/interactive/theme/theme.ts";
// Exact-pid collection of children whose owning thread is gone (#1962)
export { collectOrphanedChildren } from "./modes/rpc/child-reaper.ts";
// Shell utilities
export { withBundledBunCommands } from "./utils/bundled-bun.ts";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.ts";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.ts";
export { convertToPng } from "./utils/image-convert.ts";
export { formatDimensionNote, type ResizedImage, resizeImage } from "./utils/image-resize.ts";
export { detectSupportedImageMimeTypeFromFile } from "./utils/mime.ts";
export { getPowerShellConfig, getShellConfig } from "./utils/shell.ts";
