import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const builtinRoot = join(process.cwd(), "src", "core", "extensions", "builtin");

describe("synced builtin extensions", () => {
	it("records the external source package versions used for vendored builtins", () => {
		const manifestPath = join(builtinRoot, "external-versions.json");

		expect(existsSync(manifestPath)).toBe(true);
		const manifest = JSON.parse(readFileSync(manifestPath, "utf-8")) as {
			extensions?: Record<string, { packageName?: string; version?: string; source?: string }>;
		};

		// Generated by scripts/sync-builtin-extensions.mjs: the shape and the set of vendored ids are the
		// contract; the version values are provenance and change with every sync.
		const expectedIds = [
			"anthropic-bash",
			"anthropic-web-search",
			"bash-timeout",
			"goal",
			"gpt-apply-patch",
			"nested-agents-md",
			"openai-web-search",
			"rules",
			"todowrite",
			"webfetch",
			"websearch",
		];
		expect(Object.keys(manifest.extensions ?? {}).sort()).toEqual(expectedIds);
		for (const [id, entry] of Object.entries(manifest.extensions ?? {})) {
			expect(entry.packageName, id).toMatch(/^(@code-yeongyu\/)?pi-[a-z-]+$/);
			expect(entry.version, id).toMatch(/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/);
			expect(entry.source, id).toBe(`../pi-extensions/${entry.packageName?.replace(/^@code-yeongyu\//, "")}`);
		}
	});

	it("keeps an existing builtin directory for every pinned vendored package", () => {
		const manifest = JSON.parse(readFileSync(join(builtinRoot, "external-versions.json"), "utf-8")) as {
			extensions: Record<string, unknown>;
		};
		const directoryFor = (id: string): string => (id === "todowrite" ? "todotools" : id);

		for (const id of Object.keys(manifest.extensions)) {
			expect(existsSync(join(builtinRoot, directoryFor(id), "index.ts")), id).toBe(true);
		}
	});
});
