// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/bai.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const BAI_MODELS: ChatModelCatalog<typeof values, "bai"> =
	flattenChatModelCatalog("bai", values);

export const BAI_IMAGE_MODELS: ImageModelCatalog<typeof values, "bai"> =
	flattenImageModelCatalog("bai", values);

export const BAI_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "bai"> =
	flattenClassifierModelCatalog("bai", values);
