// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/chatgpt-subscription.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const CHATGPT_SUBSCRIPTION_MODELS: ChatModelCatalog<typeof values, "chatgpt-subscription"> =
	flattenChatModelCatalog("chatgpt-subscription", values);

export const CHATGPT_SUBSCRIPTION_IMAGE_MODELS: ImageModelCatalog<typeof values, "chatgpt-subscription"> =
	flattenImageModelCatalog("chatgpt-subscription", values);

export const CHATGPT_SUBSCRIPTION_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "chatgpt-subscription"> =
	flattenClassifierModelCatalog("chatgpt-subscription", values);
