// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/opengateway.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const OPENGATEWAY_MODELS: ChatModelCatalog<typeof values, "opengateway"> =
	flattenChatModelCatalog("opengateway", values);

export const OPENGATEWAY_IMAGE_MODELS: ImageModelCatalog<typeof values, "opengateway"> =
	flattenImageModelCatalog("opengateway", values);

export const OPENGATEWAY_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "opengateway"> =
	flattenClassifierModelCatalog("opengateway", values);
