// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/venice.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const VENICE_MODELS: ChatModelCatalog<typeof values, "venice"> =
	flattenChatModelCatalog("venice", values);

export const VENICE_IMAGE_MODELS: ImageModelCatalog<typeof values, "venice"> =
	flattenImageModelCatalog("venice", values);

export const VENICE_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "venice"> =
	flattenClassifierModelCatalog("venice", values);
